// Code generated from api.json by gova-builder. DO NOT EDIT.
package handlers

import (
	"github.com/go-chi/chi/v5"
	"gova/app/cache"
	"gova/app/db"
)

// RegisterGenerated mounts every scaffolded API route. main.go calls this once
// and is never hand-edited for routes. Framework endpoints (_version,
// _manifest) are wired directly in main.go, not here.
func RegisterGenerated(r chi.Router, database *db.DB, appCache *cache.Cache) {
	r.Get("/api/v1/bookmark_categories", BookmarkCategoryListGET(database.Read, database.Write, appCache))
	r.Post("/api/v1/bookmark_categories", BookmarkCategoryCreatePOST(database.Read, database.Write, appCache))
	r.Delete("/api/v1/bookmark_categories/{id}", BookmarkCategoryDeleteDELETE(database.Read, database.Write, appCache))
	r.Get("/api/v1/bookmark_categories/{id}", BookmarkCategoryDetailGET(database.Read, database.Write, appCache))
	r.Put("/api/v1/bookmark_categories/{id}", BookmarkCategoryUpdatePUT(database.Read, database.Write, appCache))
	r.Get("/api/v1/bookmarks", BookmarkListGET(database.Read, database.Write, appCache))
	r.Post("/api/v1/bookmarks", BookmarkCreatePOST(database.Read, database.Write, appCache))
	r.Delete("/api/v1/bookmarks/{id}", BookmarkDeleteDELETE(database.Read, database.Write, appCache))
	r.Get("/api/v1/bookmarks/{id}", BookmarkDetailGET(database.Read, database.Write, appCache))
	r.Put("/api/v1/bookmarks/{id}", BookmarkUpdatePUT(database.Read, database.Write, appCache))
	r.Get("/api/v1/clients", ClientListGET(database.Read, database.Write, appCache))
	r.Post("/api/v1/clients", ClientCreatePOST(database.Read, database.Write, appCache))
	r.Delete("/api/v1/clients/{id}", ClientDeleteDELETE(database.Read, database.Write, appCache))
	r.Get("/api/v1/clients/{id}", ClientDetailGET(database.Read, database.Write, appCache))
	r.Put("/api/v1/clients/{id}", ClientUpdatePUT(database.Read, database.Write, appCache))
	r.Get("/api/v1/focuses", FocusListGET(database.Read, database.Write, appCache))
	r.Post("/api/v1/focuses", FocusCreatePOST(database.Read, database.Write, appCache))
	r.Delete("/api/v1/focuses/{id}", FocusDeleteDELETE(database.Read, database.Write, appCache))
	r.Get("/api/v1/focuses/{id}", FocusDetailGET(database.Read, database.Write, appCache))
	r.Get("/api/v1/journal_entries", JournalEntryListGET(database.Read, database.Write, appCache))
	r.Post("/api/v1/journal_entries", JournalEntryCreatePOST(database.Read, database.Write, appCache))
	r.Delete("/api/v1/journal_entries/{id}", JournalEntryDeleteDELETE(database.Read, database.Write, appCache))
	r.Get("/api/v1/journal_entries/{id}", JournalEntryDetailGET(database.Read, database.Write, appCache))
	r.Put("/api/v1/journal_entries/{id}", JournalEntryUpdatePUT(database.Read, database.Write, appCache))
	r.Get("/api/v1/log_categories", LogCategoryListGET(database.Read, database.Write, appCache))
	r.Post("/api/v1/log_categories", LogCategoryCreatePOST(database.Read, database.Write, appCache))
	r.Delete("/api/v1/log_categories/{id}", LogCategoryDeleteDELETE(database.Read, database.Write, appCache))
	r.Get("/api/v1/log_categories/{id}", LogCategoryDetailGET(database.Read, database.Write, appCache))
	r.Put("/api/v1/log_categories/{id}", LogCategoryUpdatePUT(database.Read, database.Write, appCache))
	r.Get("/api/v1/log_entries", LogEntryListGET(database.Read, database.Write, appCache))
	r.Post("/api/v1/log_entries", LogEntryCreatePOST(database.Read, database.Write, appCache))
	r.Delete("/api/v1/log_entries/{id}", LogEntryDeleteDELETE(database.Read, database.Write, appCache))
	r.Get("/api/v1/log_entries/{id}", LogEntryDetailGET(database.Read, database.Write, appCache))
	r.Get("/api/v1/reminders", ReminderListGET(database.Read, database.Write, appCache))
	r.Post("/api/v1/reminders", ReminderCreatePOST(database.Read, database.Write, appCache))
	r.Delete("/api/v1/reminders/{id}", ReminderDeleteDELETE(database.Read, database.Write, appCache))
	r.Get("/api/v1/reminders/{id}", ReminderDetailGET(database.Read, database.Write, appCache))
	r.Put("/api/v1/reminders/{id}", ReminderUpdatePUT(database.Read, database.Write, appCache))
	r.Post("/api/v1/reminders/{id}/toggle", ReminderTogglePOST(database.Read, database.Write, appCache))
	r.Get("/api/v1/shortcuts", ShortcutListGET(database.Read, database.Write, appCache))
	r.Post("/api/v1/shortcuts", ShortcutCreatePOST(database.Read, database.Write, appCache))
	r.Put("/api/v1/shortcuts/reorder", ShortcutReorderPUT(database.Read, database.Write, appCache))
	r.Delete("/api/v1/shortcuts/{id}", ShortcutDeleteDELETE(database.Read, database.Write, appCache))
	r.Get("/api/v1/shortcuts/{id}", ShortcutDetailGET(database.Read, database.Write, appCache))
	r.Get("/api/v1/subtasks", SubtaskListGET(database.Read, database.Write, appCache))
	r.Post("/api/v1/subtasks", SubtaskCreatePOST(database.Read, database.Write, appCache))
	r.Delete("/api/v1/subtasks/{id}", SubtaskDeleteDELETE(database.Read, database.Write, appCache))
	r.Get("/api/v1/subtasks/{id}", SubtaskDetailGET(database.Read, database.Write, appCache))
	r.Put("/api/v1/subtasks/{id}", SubtaskUpdatePUT(database.Read, database.Write, appCache))
	r.Post("/api/v1/subtasks/{id}/toggle", SubtaskTogglePOST(database.Read, database.Write, appCache))
	r.Get("/api/v1/todo_blocks", TodoBlockListGET(database.Read, database.Write, appCache))
	r.Post("/api/v1/todo_blocks", TodoBlockCreatePOST(database.Read, database.Write, appCache))
	r.Delete("/api/v1/todo_blocks/{id}", TodoBlockDeleteDELETE(database.Read, database.Write, appCache))
	r.Get("/api/v1/todo_blocks/{id}", TodoBlockDetailGET(database.Read, database.Write, appCache))
	r.Put("/api/v1/todo_blocks/{id}", TodoBlockUpdatePUT(database.Read, database.Write, appCache))
	r.Get("/api/v1/todo_lists", TodoListListGET(database.Read, database.Write, appCache))
	r.Post("/api/v1/todo_lists", TodoListCreatePOST(database.Read, database.Write, appCache))
	r.Delete("/api/v1/todo_lists/{id}", TodoListDeleteDELETE(database.Read, database.Write, appCache))
	r.Get("/api/v1/todo_lists/{id}", TodoListDetailGET(database.Read, database.Write, appCache))
	r.Put("/api/v1/todo_lists/{id}", TodoListUpdatePUT(database.Read, database.Write, appCache))
	r.Post("/api/v1/todo_lists/{id}/clear_completed", TodoListClearCompletedPOST(database.Read, database.Write, appCache))
	r.Get("/api/v1/todos", TodoListGET(database.Read, database.Write, appCache))
	r.Post("/api/v1/todos", TodoCreatePOST(database.Read, database.Write, appCache))
	r.Put("/api/v1/todos/reorder", TodoReorderPUT(database.Read, database.Write, appCache))
	r.Delete("/api/v1/todos/{id}", TodoDeleteDELETE(database.Read, database.Write, appCache))
	r.Get("/api/v1/todos/{id}", TodoDetailGET(database.Read, database.Write, appCache))
	r.Put("/api/v1/todos/{id}", TodoUpdatePUT(database.Read, database.Write, appCache))
	r.Post("/api/v1/todos/{id}/toggle", TodoTogglePOST(database.Read, database.Write, appCache))
}
